{
 "title": "Global performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Balance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "measurement": "balance",
     "select": [
      [
       { "params": [ "balance" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PNL",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pnl",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Orders",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "bot" ], "type": "tag" }
     ],
     "measurement": "order",
     "select": [
      [
       { "params": [ "way" ], "type": "field" }
      ],
      [
       { "params": [ "price" ], "type": "field" }
      ],
      [
       { "params": [ "cost" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}