{
 "title": "MACD bot",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "BTC price 5m",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "price",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "measurement": "log",
     "select": [
      [
       { "params": [ "emoji" ], "type": "field" }
      ],
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Computed MACD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "MACD",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "price",
     "select": [
      [
       { "params": [ "macd" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MACD9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "price",
     "select": [
      [
       { "params": [ "macd9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PNL",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measurement": "pnl",
     "select": [
      [
       { "params": [ "usdt" ], "type": "field" }
      ],
      [
       { "params": [ "percentage" ], "type": "field" }
      ],
      [
       { "params": [ "true_percentage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total PNL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "pnl",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total PNL",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "pnl",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Orders",
   "type": "table",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 28 },
   "targets": [
    {
     "measurement": "order",
     "select": [
      [
       { "params": [ "way" ], "type": "field" }
      ],
      [
       { "params": [ "price" ], "type": "field" }
      ],
      [
       { "params": [ "cost" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}